name: Web deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .env file
        run: |  
          pwd
          mkdir assets
          pwd
          touch assets/.env
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /tpr-vet-web/
          targetBranch: main
